version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5121:5121"
    env_file:
      - ./backend/.env
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8094:8094"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
