  backend:
    image: hostel-backend
    container_name: hostel-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5112:5111"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}  # Ensure Mongo URI is set from your .env
    depends_on:
      - mongo
    networks:
      - hostel-network
    env_file:
      - .env  # Load the environment variables from your .env file
