version: "3.8"

services:
  backend:
    image: hostel-backend
    container_name: hostel-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5111:5111"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - hostel-network

  frontend:
    image: hostel-frontend
    container_name: hostel-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - hostel-network

  mongo:
    image: mongo
    container_name: hostel-mongo
    ports:
      - "27017:27017"
    networks:
      - hostel-network
    volumes:
      - mongo-data:/data/db

networks:
  hostel-network:

volumes:
  mongo-data:

